# Generated by Django 4.2 on 2023-05-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPAapp', '0006_be_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIP_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('question1', models.CharField(max_length=10)),
                ('question2', models.CharField(max_length=10)),
                ('question3', models.CharField(max_length=10)),
                ('question4', models.CharField(max_length=10)),
                ('question5', models.CharField(max_length=10)),
                ('question6', models.CharField(max_length=10)),
            ],
        ),
    ]
