# Generated by Django 4.1.7 on 2023-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPAapp', '0007_dip_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present_students', models.IntegerField()),
                ('total_students', models.IntegerField(default=60)),
            ],
        ),
    ]
