# Generated by Django 4.2 on 2023-05-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPAapp', '0008_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BE_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present_students', models.IntegerField()),
                ('total_students', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='CP_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present_students', models.IntegerField()),
                ('total_students', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='DIP_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present_students', models.IntegerField()),
                ('total_students', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='MECH_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present_students', models.IntegerField()),
                ('total_students', models.IntegerField(default=60)),
            ],
        ),
    ]
