# Generated by Django 4.2 on 2023-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPAapp', '0009_be_attendance_cp_attendance_dip_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_ca1', models.CharField(max_length=20)),
                ('marks_ca1', models.IntegerField()),
                ('out_of_ca1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_ca2', models.CharField(max_length=20)),
                ('marks_ca2', models.IntegerField()),
                ('out_of_ca2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EndSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_endsem', models.CharField(max_length=20)),
                ('marks_endsem', models.IntegerField()),
                ('out_of_endsem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MidSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_midsem', models.CharField(max_length=20)),
                ('marks_midsem', models.IntegerField()),
                ('out_of_midsem', models.IntegerField()),
            ],
        ),
    ]
