# Generated by Django 4.1.7 on 2023-05-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPAapp', '0010_ca1_ca2_endsemester_midsemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca1',
            name='out_of_ca1',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='ca2',
            name='out_of_ca2',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='endsemester',
            name='out_of_endsem',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='midsemester',
            name='out_of_midsem',
            field=models.IntegerField(default=20),
        ),
    ]
