# Generated by Django 4.1.7 on 2023-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPAapp', '0014_dip_ca1_dip_ca2_dip_endsemester_dip_midsemester'),
    ]

    operations = [
        migrations.CreateModel(
            name='BE_CA1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_ca1', models.CharField(max_length=20)),
                ('marks_ca1', models.IntegerField()),
                ('out_of_ca1', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='BE_CA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_ca2', models.CharField(max_length=20)),
                ('marks_ca2', models.IntegerField()),
                ('out_of_ca2', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='BE_EndSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_endsem', models.CharField(max_length=20)),
                ('marks_endsem', models.IntegerField()),
                ('out_of_endsem', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='BE_MidSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn_midsem', models.CharField(max_length=20)),
                ('marks_midsem', models.IntegerField()),
                ('out_of_midsem', models.IntegerField(default=20)),
            ],
        ),
    ]
